import { createHash } from "node:crypto";
import { db } from "../db";
import { logger } from "../logger";
import { truncate } from "../ai/text";
import { runStructuredPrompt } from "../ai/run";
import { recommendationPrompt } from "../ai/prompts";
import { getProjectMastery, getWeakConcepts } from "./mastery";
import { recordActivity } from "../activity";
import { publish } from "../events/bus";

/**
 * Learning recommendations (PRD §32).
 *
 * Recommendations are generated by a background workflow off the back of
 * meaningful events, not synthesised on page load. That keeps the dashboard
 * fast and means the recommendation reflects a considered view of the
 * learner's state rather than whatever was cheap to compute in a request.
 *
 * Idempotency: each recommendation carries a dedupeKey derived from the state
 * that produced it. Regenerating from the same state updates the existing row
 * instead of stacking near-identical advice (PRD §50).
 */

export interface RecommendationView {
  id: string;
  title: string;
  body: string;
  actionType: string;
  actionPayload: Record<string, unknown>;
  conceptIds: string[];
  rationale: string;
  priority: number;
  createdAt: Date;
}

export async function generateRecommendation(params: {
  projectId: string;
  userId: string;
  traceId: string;
}): Promise<string | null> {
  const project = await db.project.findFirst({
    where: { id: params.projectId, userId: params.userId },
  });
  if (!project) return null;

  const [mastery, weak, materialCount, recentAnswers, previous, lastActivity] =
    await Promise.all([
      getProjectMastery(params.projectId),
      getWeakConcepts(params.projectId, 4),
      db.material.count({ where: { projectId: params.projectId, status: "READY" } }),
      db.quizAnswer.findMany({
        where: { quiz: { projectId: params.projectId } },
        orderBy: { answeredAt: "desc" },
        take: 12,
        include: { question: { include: { concept: true } } },
      }),
      db.recommendation.findMany({
        where: { projectId: params.projectId },
        orderBy: { createdAt: "desc" },
        take: 4,
        select: { title: true },
      }),
      db.activityEvent.findFirst({
        where: { projectId: params.projectId },
        orderBy: { createdAt: "desc" },
        select: { createdAt: true },
      }),
    ]);

  const correct = recentAnswers.filter((a) => a.isCorrect).length;
  const recentAccuracy = recentAnswers.length > 0 ? correct / recentAnswers.length : 0;
  const daysSinceLastActivity = lastActivity
    ? Math.floor((Date.now() - lastActivity.createdAt.getTime()) / 86_400_000)
    : 0;

  const input = {
    projectName: project.name,
    goal: project.goal,
    materialCount,
    weakConcepts: weak.map((c) => ({ name: c.name, level: c.level, trend: c.trend })),
    strongConcepts: mastery
      .filter((c) => c.level >= 0.75 && c.evidenceCount > 0)
      .slice(0, 4)
      .map((c) => c.name),
    recentAccuracy,
    recentMistakes: recentAnswers
      .filter((a) => !a.isCorrect)
      .slice(0, 4)
      .map(
        (a) =>
          `${a.question.concept?.name ?? "General"}: ${truncate(a.question.prompt, 100)}`,
      ),
    previousRecommendations: previous.map((p) => p.title),
    daysSinceLastActivity,
  };

  let generated;
  try {
    const result = await runStructuredPrompt(recommendationPrompt, input, {
      traceId: params.traceId,
      userId: params.userId,
      projectId: params.projectId,
    });
    generated = result.value;
  } catch (error) {
    logger.error("recommendation_generation_failed", { projectId: params.projectId, error });
    return null;
  }

  // Map returned concept names back to ids so the CTA can target them.
  const conceptIds = generated.conceptNames
    .map((name) => mastery.find((m) => m.name.toLowerCase() === name.toLowerCase())?.conceptId)
    .filter((id): id is string => Boolean(id));

  // The dedupe key is a fingerprint of the *state* the advice was derived
  // from, so identical circumstances update one row rather than creating many.
  const dedupeKey = createHash("sha1")
    .update(
      [
        generated.actionType,
        conceptIds.sort().join(","),
        weak
          .slice(0, 2)
          .map((w) => `${w.conceptId}:${Math.round(w.level * 10)}`)
          .join(","),
        materialCount === 0 ? "no-materials" : "has-materials",
      ].join("|"),
    )
    .digest("hex")
    .slice(0, 24);

  const actionPayload: Record<string, unknown> = {
    conceptIds,
    conceptNames: generated.conceptNames,
  };
  if (generated.actionType === "ASK_TUTOR") {
    actionPayload.prompt = generated.conceptNames.length
      ? `Explain ${generated.conceptNames[0]} to me, and give an example from my materials.`
      : "What should I focus on next?";
  }

  const record = await db.recommendation.upsert({
    where: { projectId_dedupeKey: { projectId: params.projectId, dedupeKey } },
    create: {
      userId: params.userId,
      projectId: params.projectId,
      title: generated.title,
      body: generated.body,
      actionType: generated.actionType,
      actionPayload: JSON.stringify(actionPayload),
      conceptIds: JSON.stringify(conceptIds),
      rationale: generated.rationale,
      priority: generated.priority,
      status: "ACTIVE",
      generatedBy: "WORKFLOW",
      promptVersion: `${recommendationPrompt.id}@${recommendationPrompt.version}`,
      dedupeKey,
      expiresAt: new Date(Date.now() + 14 * 86_400_000),
    },
    update: {
      title: generated.title,
      body: generated.body,
      priority: generated.priority,
      rationale: generated.rationale,
      status: "ACTIVE",
      updatedAt: new Date(),
      expiresAt: new Date(Date.now() + 14 * 86_400_000),
    },
  });

  // Keep the surface small: older active advice is superseded, not stacked.
  await db.recommendation.updateMany({
    where: {
      projectId: params.projectId,
      status: "ACTIVE",
      id: { not: record.id },
      createdAt: { lt: record.createdAt },
    },
    data: { status: "SUPERSEDED" },
  });

  await recordActivity({
    userId: params.userId,
    projectId: params.projectId,
    type: "RECOMMENDATION_GENERATED",
    summary: generated.title,
    payload: { recommendationId: record.id, actionType: generated.actionType },
  });

  await publish(
    "RECOMMENDATION_GENERATED",
    { projectId: params.projectId, recommendationId: record.id },
    { userId: params.userId, projectId: params.projectId },
  );

  return record.id;
}

export async function activeRecommendations(
  projectId: string,
  limit = 3,
): Promise<RecommendationView[]> {
  const rows = await db.recommendation.findMany({
    where: {
      projectId,
      status: "ACTIVE",
      OR: [{ expiresAt: null }, { expiresAt: { gt: new Date() } }],
    },
    orderBy: [{ priority: "desc" }, { createdAt: "desc" }],
    take: limit,
  });

  return rows.map((row) => ({
    id: row.id,
    title: row.title,
    body: row.body,
    actionType: row.actionType,
    actionPayload: JSON.parse(row.actionPayload || "{}"),
    conceptIds: JSON.parse(row.conceptIds || "[]"),
    rationale: row.rationale,
    priority: row.priority,
    createdAt: row.createdAt,
  }));
}

/** Cross-project "what next" for the home dashboard. */
export async function topRecommendationsForUser(userId: string, limit = 3) {
  return db.recommendation.findMany({
    where: {
      userId,
      status: "ACTIVE",
      OR: [{ expiresAt: null }, { expiresAt: { gt: new Date() } }],
    },
    orderBy: [{ priority: "desc" }, { createdAt: "desc" }],
    take: limit,
    include: { project: { select: { id: true, name: true, spaceId: true } } },
  });
}
